name: Deploy to S3 with Versioning

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set release version
      run: |
        echo "RELEASE_VERSION=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        echo "RELEASE_VERSION folder will be: $RELEASE_VERSION"

    - name: Deploy versioned build to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: raasystem.net
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
        SOURCE_DIR: './'
        DEST_DIR: ${{ env.RELEASE_VERSION }}

    - name: Update latest pointer
      run: aws s3 sync ./ s3://raasystem.net/latest/ --delete --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
